## Basic Configuration
baseurl = "http://localhost:1313/"
languageCode = "en"
title = "Tucson Footie"
theme = "hyde-hyde"
rss = true

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

paginate = 5

## Site Settings
[params]
    author = "Author"
    title = "Tucson Footie"
    description = "Soccer in the Old Pueblo"
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    themeColor = "theme-base-0f"
    # sidebar, copyright & license
    copyright = "cpoff"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "<username>"
    instagram = "<username>"
    xing = "<username>"
    linkedin = "<username>"
    twitter = "<username>"
    facebook = "<username>"
    stackoverflow = "<username>"
    telegram = "<username>"
    email = "your-email@example.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Schedule"
    identifier = "schedule"
    weight = 200
    url = "/schedule/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
